---
- name: Ensure old versions of Docker are not Installed.
  package:
    name:
    - docker
    - docker-common
    - docker-engine
    state: absent

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Docker.
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - containerd.io
  - docker-ce
  - docker-ce-cli
  notify: restart docker

- name: Create Docker configuration directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root

- name: Copy Docker configuration file
  copy:
    src: docker.daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root

- name: Create Docker systemd service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    daemon_reload: yes
    state: started
    enabled: true

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- name: Ensure vagrant user is added to the docker group.
  user:
    name: vagrant
    groups: docker
    append: true
