- name: Check that cluster has been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init_result

- name: Initialize Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name {{ node_name }} --pod-network-cidr=192.168.0.0/16
  when: kubeadm_init_result.stat.exists == False

- name: Create .kube folder for vagrant user
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy kubeconfig to vagrant user folder
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant

- name: Install Calico POD network
  become: no
  command: kubectl create -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- name: Copy kubeconfig to local file
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    flat: yes

- name: Taint nodes
  become: no
  command: kubectl taint nodes --all node-role.kubernetes.io/master-

- name: Configure master nodes firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
  - 6443/tcp
  - 2379-2380/tcp
  - 10250-10252/tcp
  - 10255/tcp
  - 8472/udp
  - 30000-32767/tcp
  notify: restart firewalld
