- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  become: yes

- name: Configure master nodes firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
  - 10250/tcp
  - 10255/tcp
  - 8472/udp
  - 30000-32767/tcp
  notify: restart firewalld
